### ISSUE TITLE
Color each particle differently?

### ISSUE THREAD

**Issue by JoshuaBatty** [kuflex/MorphOpenCL#1]
Hey dude this is a really cool example. Was just checking if you knew how to draw each particle with a different color? Specifically I want to be able to have an image that contains color and have that color information used to color each particle...? Any ideas. Thanks!

**Comment by sodazot** [comment]
Hi Joshua!
Thanx!
It is possible to draw particles in different colors.
We are busy with hard work now.
And we will make this example on github about a week later.

## Igor

http://kuflex.com

## http://sodazot.com

tel. (916) 646 3173
skype: sodazot

**Comment by JoshuaBatty** [comment]
Great thanks Igor! Looking forward to checking it out!

**Comment by perevalovds** [comment]
Hi Joshua,
we had made morphing between color images,
Video: http://www.youtube.com/watch?v=J3RJgYcQi-k
Code: https://github.com/kuflex/examples/tree/master/Morph-images

Comparing with previous gray-scale example, here we create one additiinal VBO buffer holding colors, and use it in OpenCL computations and in drawing.

Hope, it helps you with your project! :)

**Comment by JoshuaBatty** [comment]
Agh awesome thanks for that. I had managed to hack something together that did something similar but its good to see how to do it properly. Thanks!
